#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_accueil:

  path: /
  controller: App\Controller\AccueilController::index

#----------------------------------------------------------

app_ComptableConnexion:
  path: /Comptable/Connexion
  controller: App\Controller\ComptableController::connexion

app_ComptableConnecter:
  path: /Comptable/Connecter
  controller: App\Controller\ComptableController::connecter

app_ComptableAccueil:
  path: /Comptable/Accueil
  controller: App\Controller\ComptableController::accueil

app_ComptableValiderFicheFrais:
  path: /Comptable/ValiderFicheFrais
  controller: App\Controller\ComptableController::validerFicheFrais

app_ComptableModifierFicheFrais:
  path: /Comptable/modifierFicheFrais
  controller: App\Controller\ComptableController::refuserFicheFrais
  
app_ComptableValider:
  path: /Comptable/valider
  controller: App\Controller\ComptableController::valider

app_ComptableModifierFraisForfait:
  path: /Comptable/modifierFraisForfait
  controller: App\Controller\ComptableController::modifierFraisForfait


#----------------------------------------------------------

app_VisiteurConnexion:
  path: /Visiteur/Connexion
  controller: App\Controller\VisiteurController::connexion

app_VisiteurConncter:
  path: /Visiteur/Connecter
  controller: App\Controller\VisiteurController::connecter

app_VisiteurAccueil:
  path: /Visiteur/Accueil
  controller: App\Controller\VisiteurController::accueil

app_VisiteurVoirFicheFrais:
  path: /Visiteur/FicheFrais
  controller: App\Controller\VisiteurController::voirFicheFrais

