#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_accueil:

  path: /
  controller: App\Controller\AccueilController::index


#Visiteur-------------------------------------------------------------


app_VisiteurConnexion:
  path: /Visiteur/Connexion
  controller: App\Controller\VisiteurController::connexion

app_VisiteurConnecter:
  path: /Visiteur/Connecter
  controller: App\Controller\VisiteurController::connecter

app_VisiteurDeconnecter:
  path: /Visiteur/Deconnecter
  controller: App\Controller\VisiteurController::deconnecter

app_VisiteurAccueil:
  path: /Visiteur/Accueil
  controller: App\Controller\VisiteurController::accueil

app_VisiteurConsulterVue:
  path: /Visiteur/Consulter
  controller: App\Controller\VisiteurController::consulterVue 

app_VisiteurConsulterVueRetour:
  path: /Visiteur/retourConsulter
  controller: App\Controller\VisiteurController::retourConsulterVue 

app_VisiteurConsulter:
  path: /Visiteur/ConsulterResultat
  controller: App\Controller\VisiteurController::consulter 

app_VisiteurConsulterRetour:
  path: /Visiteur/ConsulterResultatRetour
  controller: App\Controller\VisiteurController::retourConsulter 

app_VisiteurFicheFraisVue:
  path: /Visiteur/FicheDeFrais
  controller: App\Controller\VisiteurController::ficheFraisVue 


app_VisiteurFicheFraisVueRetour:
  path: /Visiteur/FicheDeFraisRetour
  controller: App\Controller\VisiteurController::ficheFraisVueRetour

app_VisiteurFicheFrais:
  path: /Visiteur/FicheDeFraisController
  controller: App\Controller\VisiteurController::ficheFrais 

app_SupprimerFicheHorsForfait:
  path: /Visiteur/SupprimerFicheHorsForfait
  controller: App\Controller\VisiteurController::supprimerFicheHorsForfait
  methods: [POST]

