<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZvjxfer\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZvjxfer/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZvjxfer.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZvjxfer\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZvjxfer\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zvjxfer',
    'container.build_id' => 'd1a07f1a',
    'container.build_time' => 1681934026,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZvjxfer');
